#define IS_PIE 0
#define LIBC_START_MAIN_ADDR_TYPE CODE
#define LIB_C_START_MAIN_ADDR 0x80490d0
#define FIRST_ENTRY_OFFSET 0x6000
#define CONFIG_LOADER_TYPE LOAD_FROM_MEM
#define PATCH_DATA_MMAP_FILE_SIZE 0x1e94d
#define PATCH_DATA_MMAP_FILE_VADDR 0x804f000
