#define IS_PIE 1
#define LIBC_START_MAIN_ADDR_TYPE CODE
#define LIB_C_START_MAIN_ADDR 0x8f0
#define FIRST_ENTRY_OFFSET 0x204000
#define CONFIG_LOADER_TYPE LOAD_FROM_SHARE_MEM
#define PATCH_DATA_SHARE_MEM_ID 124
#define PATCH_DATA_MMAP_FILE_SIZE 0xbee6
