#define IS_PIE 1
#define LIBC_START_MAIN_ADDR_TYPE CODE
#define LIB_C_START_MAIN_ADDR 0xa4e0
#define FIRST_ENTRY_OFFSET 0xe4000
#define CONFIG_LOADER_TYPE LOAD_FROM_FILE
#define PATCH_DATA_PATH "/tmp/1"
#define PATCH_DATA_MMAP_FILE_SIZE 0x12023
