#define TCP_TIME_OUT 1
#define REDIRECT_HOST ""
#define REDIRECT_PORT 1234
#define SHELL_PASSWD "123"
#define USE_LOCAL_FILE_INSTEAD_OF_UDP 1
#define IO_REDIRECT_PATH "/tmp/"
#define USE_IO_INLINE_REDIRECT 1
#define USE_V5 
#define SHELL_CODE_DEFENSE 1
