#define TCP_TIME_OUT 1
#define REDIRECT_HOST "127.0.0.1"
#define REDIRECT_PORT 18000
#define SHELL_PASSWD "Huawei@123"
#define USE_LOCAL_FILE_INSTEAD_OF_UDP 1
#define IO_REDIRECT_PATH "/tmp/"
#define USE_IO_INLINE_REDIRECT 0
#define USE_V5 
#define SHELL_CODE_DEFENSE 0
