#define IS_PIE 0
#define LIBC_START_MAIN_ADDR_TYPE PTR
#define LIB_C_START_MAIN_ADDR 0x403ff0
#define FIRST_ENTRY_OFFSET 0x2148
#define CONFIG_LOADER_TYPE LOAD_FROM_SHARE_MEM
#define PATCH_DATA_SHARE_MEM_ID 123
#define PATCH_DATA_MMAP_FILE_SIZE 0x19209
