#define LIBC_START_MAIN_ADDR_TYPE PTR
#define LIB_C_START_MAIN_ADDR 0x201fe0
#define USE_V5 
#define FIRST_ENTRY_OFFSET 0xc70
#define CONFIG_LOADER_TYPE LOAD_FROM_FILE
#define PATCH_DATA_PATH "/tmp/1"
#define PATCH_DATA_MMAP_FILE_SIZE 0x1803d
