#define LIBC_START_MAIN_ADDR_TYPE CODE
#define LIB_C_START_MAIN_ADDR 0x10d0
#define USE_V5 
#define EH_FRAME_SHDR 0x215c
#define LIBC_CSU_INIT_ADDR "0x15f0"
#define OFFSET "0x494"
#define FIRST_ENTRY_OFFSET 0x215c
#define CONFIG_LOADER_TYPE LOAD_FROM_FILE
#define PATCH_DATA_PATH "/a"
#define PATCH_DATA_MMAP_FILE_SIZE 0x299fd
