#define IS_PIE 1
#define LIBC_START_MAIN_ADDR_TYPE PTR
#define LIB_C_START_MAIN_ADDR 0x3fe0
#define FIRST_ENTRY_OFFSET 0x2288
#define CONFIG_LOADER_TYPE LOAD_FROM_MEM
#define PATCH_DATA_MMAP_FILE_SIZE 0xcefc
#define PATCH_DATA_MMAP_FILE_VADDR 0x6000
