#define LIBC_START_MAIN_ADDR_TYPE CODE
#define LIB_C_START_MAIN_ADDR 0x10d0
#define USE_V5 
#define EH_FRAME_SHDR 0x215c
#define FIRST_ENTRY_OFFSET 0x0
#define CONFIG_LOADER_TYPE LOAD_FROM_FILE
#define PATCH_DATA_PATH "/tmp/2"
#define PATCH_DATA_MMAP_FILE_SIZE 0xec5a
